site_name: AkuManusiaaWeb
site_url: http://ex.com

nav:
  - Beranda: index.md
  - Cerita:
    - cerita/index.md
    - Lorem Ipsum: cerita/lorem.md
    - Cerita Kantor: cerita/kantor.md
  - Add-on Minecraft: addon.md
extra_css:
  - stylesheets/style.css
theme:
  logo: img/icon.png
  favicon: img/icon.png
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.indexes
    - search.suggest
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Ganti ke mode terang

    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7 
        name: Ganti ke mode gelap
plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem